USE [CAR_RENT]
GO

/****** Object:  Table [dbo].[CLIENTS]    Script Date: 05.05.2022 18:16:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CLIENTS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USER_TYPE] [nvarchar](20) default '0',
	[LOGIN] [nvarchar](50) NULL,
	[PASSWORD] [nvarchar](50) NULL,
	[SURNAME] [nvarchar](50) NULL,
	[NAME] [nvarchar](50) NULL,
	[PATRONYMIC] [nvarchar](50) NULL,
	[BDAY] [date] NULL,
	[PASSPORT_SERIES] [nvarchar](10) NULL,
	[PASSPORT_ID] [int] NULL,
	[DRIVER_LICENSE_ID] [nvarchar](30) NULL,
	[DRIVING_EXPERIENCE] [nvarchar](20) NULL,
	[TELEPHONE] [nvarchar](30) NULL,
	[ADRESS] [nvarchar](30) NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


