//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAR_RENT.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCIDENT
    {
        public int ID { get; set; }
        public int CONTRACT_ID { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<int> DAMAGE_COST { get; set; }
        public string DAMAGE_DESCRIPTION { get; set; }
    
        public virtual CONTRACT CONTRACT { get; set; }
    }
}
