//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAR_RENT.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CAR()
        {
            this.CONTRACTS = new HashSet<CONTRACT>();
        }
    
        public int ID { get; set; }
        public string BREND { get; set; }
        public string MODEL { get; set; }
        public string CLASS { get; set; }
        public string REGISTRATION_NUMBER { get; set; }
        public string STATUS { get; set; }
        public string IMAGE { get; set; }
        public Nullable<int> RENT_PRICE { get; set; }
    
        public virtual MODEL_INFO MODEL_INFO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRACT> CONTRACTS { get; set; }
    }
}
