//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAR_RENT.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENT()
        {
            this.CONTRACTS = new HashSet<CONTRACT>();
            this.USER_TYPE = "0";
        }
    
        public int ID { get; set; }
        public string LOGIN { get; set; }
        public string PASSWORD { get; set; }
        public string SURNAME { get; set; }
        public string NAME { get; set; }
        public string PATRONYMIC { get; set; }
        public Nullable<System.DateTime> BDAY { get; set; }
        public string PASSPORT_SERIES { get; set; }
        public Nullable<int> PASSPORT_ID { get; set; }
        public string DRIVER_LICENSE_ID { get; set; }
        public string DRIVING_EXPERIENCE { get; set; }
        public string TELEPHONE { get; set; }
        public string ADRESS { get; set; }
        public string USER_TYPE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRACT> CONTRACTS { get; set; }
    }
}
