//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAR_RENT.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRACT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONTRACT()
        {
            this.ACCIDENTS = new HashSet<ACCIDENT>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CLIENT_ID { get; set; }
        public Nullable<int> CAR_ID { get; set; }
        public Nullable<System.DateTime> CONTRACT_START { get; set; }
        public Nullable<System.DateTime> CONTRACT_END { get; set; }
        public string PROMO_CODE { get; set; }
        public Nullable<int> TOTAL_COST { get; set; }
        public string STATUS { get; set; }
        public string CONTRACT_STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACCIDENT> ACCIDENTS { get; set; }
        public virtual CAR CAR { get; set; }
        public virtual CLIENT CLIENT { get; set; }
        public virtual PROMO_CODE PROMO_CODE1 { get; set; }
    }
}
