//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAR_RENT.models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CAR_RENTEntities : DbContext
    {
      
        public CAR_RENTEntities()
            : base("name=CAR_RENTEntities")
        {
        }
        private static CAR_RENTEntities context;
        public static CAR_RENTEntities GetContext()
        {
            if (context == null)
                context = new CAR_RENTEntities();
            return context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCIDENT> ACCIDENTS { get; set; }
        public virtual DbSet<CAR> CARS { get; set; }
        public virtual DbSet<CLIENT> CLIENTS { get; set; }
        public virtual DbSet<CONTRACT> CONTRACTS { get; set; }
        public virtual DbSet<MODEL_INFO> MODEL_INFO { get; set; }
        public virtual DbSet<PROMO_CODE> PROMO_CODE { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
