//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAR_RENT.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MODEL_INFO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MODEL_INFO()
        {
            this.CARS = new HashSet<CAR>();
        }
    
        public string MODEL { get; set; }
        public Nullable<System.DateTime> YEAR_OF_ISSUE { get; set; }
        public string BODY_TYPE { get; set; }
        public string ENGINE_CAPACITY { get; set; }
        public string ENGINE_TYPE { get; set; }
        public string TRANSMISSION { get; set; }
        public string EQUIPMENT { get; set; }
        public int ID { get; set; }
        public string BREND { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CAR> CARS { get; set; }

        public CAR CAR
        {
            get => default;
            set
            {
            }
        }
    }
}
