//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAR_RENT.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROMO_CODE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROMO_CODE()
        {
            this.CONTRACTS = new HashSet<CONTRACT>();
        }
    
        public string PROMO_CODE1 { get; set; }
        public string DISCOUNT_AMOUNT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONTRACT> CONTRACTS { get; set; }

        public CONTRACT CONTRACT
        {
            get => default;
            set
            {
            }
        }
    }
}
